app:
    title: Teste
    css:
        bootstrap:
            file: bootstrap.min.css
            media: all
        bootstrap-theme:
            file: bootstrap-theme.css
            media: all
        custom:
            file: custom-style.css
            media: all
    js:
        bootstrap:
            file: bootstrap.min.js
database:
    host: localhost
    username: root
    password: 123
    dbname: teixeira_classificados